// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_locale_private_middleware from './routes/[locale]/(private)/_middleware.ts';
import * as $_locale_private_admin_dashboard from './routes/[locale]/(private)/admin/dashboard.tsx';
import * as $_locale_public_slug_ from './routes/[locale]/(public)/[slug].tsx';
import * as $_locale_public_footer from './routes/[locale]/(public)/_footer.tsx';
import * as $_locale_public_header from './routes/[locale]/(public)/_header.tsx';
import * as $_locale_public_layout from './routes/[locale]/(public)/_layout.tsx';
import * as $_locale_public_auth_middleware from './routes/[locale]/(public)/auth/_middleware.tsx';
import * as $_locale_public_auth_active from './routes/[locale]/(public)/auth/active.tsx';
import * as $_locale_public_auth_index from './routes/[locale]/(public)/auth/index.tsx';
import * as $_locale_public_auth_login from './routes/[locale]/(public)/auth/login.tsx';
import * as $_locale_public_auth_logout from './routes/[locale]/(public)/auth/logout.ts';
import * as $_locale_public_auth_register_success from './routes/[locale]/(public)/auth/register-success.tsx';
import * as $_locale_public_auth_register from './routes/[locale]/(public)/auth/register.tsx';
import * as $_locale_public_auth_reset_password from './routes/[locale]/(public)/auth/reset-password.tsx';
import * as $_locale_public_auth_thank_you from './routes/[locale]/(public)/auth/thank-you.tsx';
import * as $_locale_public_index from './routes/[locale]/(public)/index.tsx';
import * as $_locale_public_partials_abc from './routes/[locale]/(public)/partials/abc.tsx';
import * as $_locale_public_product from './routes/[locale]/(public)/product.tsx';
import * as $_locale_middleware from './routes/[locale]/_middleware.ts';
import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $api_joke from './routes/api/joke.ts';
import * as $greet_name_ from './routes/greet/[name].tsx';
import * as $Carousel from './islands/Carousel.tsx';
import * as $Counter from './islands/Counter.tsx';
import * as $Galleries_ArrowButton from './islands/Galleries/ArrowButton.ts';
import * as $Galleries_DotButton from './islands/Galleries/DotButton.ts';
import * as $Galleries_TweenOpacity from './islands/Galleries/TweenOpacity.ts';
import * as $Galleries_index from './islands/Galleries/index.tsx';
import * as $ProductBuyActionsBlock_AddToCartBtn from './islands/ProductBuyActionsBlock/AddToCartBtn.tsx';
import * as $ProductBuyActionsBlock_InstantBuyBtn from './islands/ProductBuyActionsBlock/InstantBuyBtn.tsx';
import * as $ProductBuyActionsBlock_index from './islands/ProductBuyActionsBlock/index.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
	routes: {
		'./routes/[locale]/(private)/_middleware.ts': $_locale_private_middleware,
		'./routes/[locale]/(private)/admin/dashboard.tsx': $_locale_private_admin_dashboard,
		'./routes/[locale]/(public)/[slug].tsx': $_locale_public_slug_,
		'./routes/[locale]/(public)/_footer.tsx': $_locale_public_footer,
		'./routes/[locale]/(public)/_header.tsx': $_locale_public_header,
		'./routes/[locale]/(public)/_layout.tsx': $_locale_public_layout,
		'./routes/[locale]/(public)/auth/_middleware.tsx': $_locale_public_auth_middleware,
		'./routes/[locale]/(public)/auth/active.tsx': $_locale_public_auth_active,
		'./routes/[locale]/(public)/auth/index.tsx': $_locale_public_auth_index,
		'./routes/[locale]/(public)/auth/login.tsx': $_locale_public_auth_login,
		'./routes/[locale]/(public)/auth/logout.ts': $_locale_public_auth_logout,
		'./routes/[locale]/(public)/auth/register-success.tsx':
			$_locale_public_auth_register_success,
		'./routes/[locale]/(public)/auth/register.tsx': $_locale_public_auth_register,
		'./routes/[locale]/(public)/auth/reset-password.tsx': $_locale_public_auth_reset_password,
		'./routes/[locale]/(public)/auth/thank-you.tsx': $_locale_public_auth_thank_you,
		'./routes/[locale]/(public)/index.tsx': $_locale_public_index,
		'./routes/[locale]/(public)/partials/abc.tsx': $_locale_public_partials_abc,
		'./routes/[locale]/(public)/product.tsx': $_locale_public_product,
		'./routes/[locale]/_middleware.ts': $_locale_middleware,
		'./routes/_404.tsx': $_404,
		'./routes/_app.tsx': $_app,
		'./routes/_middleware.ts': $_middleware,
		'./routes/api/joke.ts': $api_joke,
		'./routes/greet/[name].tsx': $greet_name_,
	},
	islands: {
		'./islands/Carousel.tsx': $Carousel,
		'./islands/Counter.tsx': $Counter,
		'./islands/Galleries/ArrowButton.ts': $Galleries_ArrowButton,
		'./islands/Galleries/DotButton.ts': $Galleries_DotButton,
		'./islands/Galleries/TweenOpacity.ts': $Galleries_TweenOpacity,
		'./islands/Galleries/index.tsx': $Galleries_index,
		'./islands/ProductBuyActionsBlock/AddToCartBtn.tsx': $ProductBuyActionsBlock_AddToCartBtn,
		'./islands/ProductBuyActionsBlock/InstantBuyBtn.tsx': $ProductBuyActionsBlock_InstantBuyBtn,
		'./islands/ProductBuyActionsBlock/index.tsx': $ProductBuyActionsBlock_index,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
