// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_private_middleware from "./routes/(private)/_middleware.ts";
import * as $_public_auth_middleware from "./routes/(public)/auth/_middleware.tsx";
import * as $_public_auth_active from "./routes/(public)/auth/active.tsx";
import * as $_public_auth_index from "./routes/(public)/auth/index.tsx";
import * as $_public_auth_login from "./routes/(public)/auth/login.tsx";
import * as $_public_auth_register from "./routes/(public)/auth/register.tsx";
import * as $_public_auth_reset_password from "./routes/(public)/auth/reset-password.tsx";
import * as $_public_auth_thank_you from "./routes/(public)/auth/thank-you.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(private)/_middleware.ts": $_private_middleware,
    "./routes/(public)/auth/_middleware.tsx": $_public_auth_middleware,
    "./routes/(public)/auth/active.tsx": $_public_auth_active,
    "./routes/(public)/auth/index.tsx": $_public_auth_index,
    "./routes/(public)/auth/login.tsx": $_public_auth_login,
    "./routes/(public)/auth/register.tsx": $_public_auth_register,
    "./routes/(public)/auth/reset-password.tsx": $_public_auth_reset_password,
    "./routes/(public)/auth/thank-you.tsx": $_public_auth_thank_you,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
